export type Company = {
  active: boolean;
  ceo: string;
  country: string;
  description: string;
  employees: number;
  hq_address: string;
  hq_country: string;
  hq_state: string;
  industry: string;
  listdate: string;
  logo: string;
  name: string;
  phone: string;
  sector: string;
  similar: string[];
  symbol: string;
  tags: string[];
  updated: string;
  url: string;
};
